-- Cross-database DDL derived from hhm-lib-core/schema/schema.sql
-- Source: hacker-house-medellin/hhm-lib-core@de8807f825048a1faf7ace3ece4f9ffddc1e45b2 (PR #6)
-- Generated by declarative-postgres-migrate (dpm) against an empty product schema
-- Provider preflight on 2026-08-30 found no public HHaus tables or private intake bucket.
-- Converges the target onto the source. Review before applying.
-- dpm never applies SQL unless explicitly told to (dpm apply --yes).

BEGIN;

-- create schema: public
CREATE SCHEMA IF NOT EXISTS "public";

-- create extension: pgcrypto
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- create table: public.hhm_applications
CREATE TABLE IF NOT EXISTS "public"."hhm_applications" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "idempotency_key" character varying(128) NOT NULL,
  "payload_sha256" character(64) NOT NULL,
  "pre_interest_id" uuid,
  "applicant_subject" character varying(255),
  "email" character varying(320) NOT NULL,
  "linkedin_url" character varying(500) NOT NULL,
  "legal_name" character varying(200) NOT NULL,
  "date_of_birth" date NOT NULL,
  "nationality" character varying(120) NOT NULL,
  "phone" character varying(32) NOT NULL,
  "current_city" character varying(160) NOT NULL,
  "github_url" character varying(500),
  "portfolio_url" character varying(500),
  "entrepreneurship_idea" character varying(8000) NOT NULL,
  "project_stage" character varying(64) NOT NULL,
  "stay_preference" character varying(32) NOT NULL,
  "preferred_start_month" date NOT NULL,
  "community_contribution" character varying(4000) NOT NULL,
  "accessibility_or_accommodation_notes" character varying(4000),
  "resume_upload_id" uuid NOT NULL,
  "photo_id_upload_id" uuid NOT NULL,
  "age_and_identity_attestation" boolean NOT NULL,
  "privacy_notice_version" character varying(64) NOT NULL,
  "status" character varying(32) NOT NULL DEFAULT 'submitted'::character varying,
  "status_version" bigint NOT NULL DEFAULT 0,
  "last_admin_operation_id" uuid,
  "mirror_status" character varying(32) NOT NULL DEFAULT 'pending'::character varying,
  "submitted_at" timestamp with time zone NOT NULL DEFAULT transaction_timestamp(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT transaction_timestamp(),
  CONSTRAINT "hhm_applications_adult" CHECK (((date_of_birth <= ((CURRENT_DATE - '18 years'::interval))::date) AND (date_of_birth >= '1900-01-01'::date))),
  CONSTRAINT "hhm_applications_attestation" CHECK (age_and_identity_attestation),
  CONSTRAINT "hhm_applications_email" CHECK ((((email)::text = btrim((email)::text)) AND (POSITION(('@'::text) IN (email)) > 1))),
  CONSTRAINT "hhm_applications_github" CHECK (((github_url IS NULL) OR ((github_url)::text ~ '^https://github\.com/'::text))),
  CONSTRAINT "hhm_applications_idea" CHECK (((char_length((entrepreneurship_idea)::text) >= 80) AND (char_length((entrepreneurship_idea)::text) <= 8000))),
  CONSTRAINT "hhm_applications_idempotency_key_key" UNIQUE (idempotency_key),
  CONSTRAINT "hhm_applications_linkedin" CHECK (((linkedin_url)::text ~ '^https://(www\.)?linkedin\.(com|cn)/in/'::text)),
  CONSTRAINT "hhm_applications_mirror" CHECK ((((mirror_status)::text = 'pending'::text) OR ((mirror_status)::text = 'mirrored'::text) OR ((mirror_status)::text = 'retryable_failure'::text) OR ((mirror_status)::text = 'terminal_failure'::text))),
  CONSTRAINT "hhm_applications_pkey" PRIMARY KEY (id),
  CONSTRAINT "hhm_applications_portfolio" CHECK (((portfolio_url IS NULL) OR ((portfolio_url)::text ~ '^https://'::text))),
  CONSTRAINT "hhm_applications_project_stage" CHECK ((((project_stage)::text = 'idea'::text) OR ((project_stage)::text = 'prototype'::text) OR ((project_stage)::text = 'early_revenue'::text) OR ((project_stage)::text = 'growing'::text) OR ((project_stage)::text = 'nonprofit_or_open_source'::text))),
  CONSTRAINT "hhm_applications_sha256" CHECK ((payload_sha256 ~ '^[a-f0-9]{64}$'::text)),
  CONSTRAINT "hhm_applications_status" CHECK ((((status)::text = 'submitted'::text) OR ((status)::text = 'under_review'::text) OR ((status)::text = 'needs_information'::text) OR ((status)::text = 'interview'::text) OR ((status)::text = 'accepted'::text) OR ((status)::text = 'waitlisted'::text) OR ((status)::text = 'declined'::text) OR ((status)::text = 'withdrawn'::text))),
  CONSTRAINT "hhm_applications_status_version" CHECK ((status_version >= 0)),
  CONSTRAINT "hhm_applications_stay" CHECK ((((stay_preference)::text = 'three_months'::text) OR ((stay_preference)::text = 'six_months'::text))),
  CONSTRAINT "hhm_applications_uploads_distinct" CHECK ((resume_upload_id <> photo_id_upload_id))
);
CREATE INDEX hhm_applications_email_idx ON public.hhm_applications USING btree (lower((email)::text));
CREATE INDEX hhm_applications_photo_id_upload_idx ON public.hhm_applications USING btree (photo_id_upload_id);
CREATE INDEX hhm_applications_pre_interest_idx ON public.hhm_applications USING btree (pre_interest_id) WHERE (pre_interest_id IS NOT NULL);
CREATE INDEX hhm_applications_resume_upload_idx ON public.hhm_applications USING btree (resume_upload_id);
CREATE INDEX hhm_applications_status_idx ON public.hhm_applications USING btree (status, submitted_at DESC);
CREATE INDEX hhm_applications_subject_idx ON public.hhm_applications USING btree (applicant_subject) WHERE (applicant_subject IS NOT NULL);

-- create table: public.hhm_intake_uploads
CREATE TABLE IF NOT EXISTS "public"."hhm_intake_uploads" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "idempotency_key" character varying(128) NOT NULL,
  "payload_sha256" character(64) NOT NULL,
  "applicant_subject" character varying(255),
  "kind" character varying(32) NOT NULL,
  "object_key" character varying(1024) NOT NULL,
  "content_sha256" character(64) NOT NULL,
  "content_type" character varying(128) NOT NULL,
  "size_bytes" bigint NOT NULL,
  "status" character varying(32) NOT NULL DEFAULT 'pending'::character varying,
  "expires_at" timestamp with time zone NOT NULL,
  "uploaded_at" timestamp with time zone,
  "verified_at" timestamp with time zone,
  "deleted_at" timestamp with time zone,
  "created_at" timestamp with time zone NOT NULL DEFAULT transaction_timestamp(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT transaction_timestamp(),
  CONSTRAINT "hhm_intake_uploads_content_sha256" CHECK ((content_sha256 ~ '^[a-f0-9]{64}$'::text)),
  CONSTRAINT "hhm_intake_uploads_idempotency_key_key" UNIQUE (idempotency_key),
  CONSTRAINT "hhm_intake_uploads_kind" CHECK ((((kind)::text = 'resume'::text) OR ((kind)::text = 'photo_id'::text))),
  CONSTRAINT "hhm_intake_uploads_lifecycle" CHECK (((((status)::text = 'pending'::text) AND (uploaded_at IS NULL) AND (verified_at IS NULL) AND (deleted_at IS NULL)) OR (((status)::text = 'uploaded'::text) AND (uploaded_at IS NOT NULL) AND (verified_at IS NULL) AND (deleted_at IS NULL)) OR ((((status)::text = 'verified'::text) OR ((status)::text = 'quarantined'::text)) AND (uploaded_at IS NOT NULL) AND (verified_at IS NOT NULL) AND (deleted_at IS NULL)) OR ((((status)::text = 'expired'::text) OR ((status)::text = 'deleted'::text)) AND (deleted_at IS NOT NULL)))),
  CONSTRAINT "hhm_intake_uploads_object_key_key" UNIQUE (object_key),
  CONSTRAINT "hhm_intake_uploads_payload_sha256" CHECK ((payload_sha256 ~ '^[a-f0-9]{64}$'::text)),
  CONSTRAINT "hhm_intake_uploads_pkey" PRIMARY KEY (id),
  CONSTRAINT "hhm_intake_uploads_size" CHECK (((size_bytes >= 1) AND (size_bytes <= 10485760))),
  CONSTRAINT "hhm_intake_uploads_status" CHECK ((((status)::text = 'pending'::text) OR ((status)::text = 'uploaded'::text) OR ((status)::text = 'verified'::text) OR ((status)::text = 'quarantined'::text) OR ((status)::text = 'expired'::text) OR ((status)::text = 'deleted'::text))),
  CONSTRAINT "hhm_intake_uploads_type" CHECK ((((content_type)::text = 'application/pdf'::text) OR ((content_type)::text = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'::text) OR ((content_type)::text = 'image/jpeg'::text) OR ((content_type)::text = 'image/png'::text) OR ((content_type)::text = 'image/heic'::text)))
);
CREATE INDEX hhm_intake_uploads_expiry_idx ON public.hhm_intake_uploads USING btree (expires_at) WHERE (deleted_at IS NULL);
CREATE INDEX hhm_intake_uploads_subject_idx ON public.hhm_intake_uploads USING btree (applicant_subject) WHERE (applicant_subject IS NOT NULL);

-- create table: public.hhm_pre_interests
CREATE TABLE IF NOT EXISTS "public"."hhm_pre_interests" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "idempotency_key" character varying(128) NOT NULL,
  "payload_sha256" character(64) NOT NULL,
  "applicant_subject" character varying(255),
  "email" character varying(320) NOT NULL,
  "linkedin_url" character varying(500) NOT NULL,
  "entrepreneurship_idea" character varying(4000) NOT NULL,
  "stay_preference" character varying(32) NOT NULL,
  "privacy_notice_version" character varying(64) NOT NULL,
  "source_host" character varying(255) NOT NULL,
  "mirror_status" character varying(32) NOT NULL DEFAULT 'pending'::character varying,
  "created_at" timestamp with time zone NOT NULL DEFAULT transaction_timestamp(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT transaction_timestamp(),
  CONSTRAINT "hhm_pre_interests_email" CHECK ((((email)::text = btrim((email)::text)) AND (POSITION(('@'::text) IN (email)) > 1))),
  CONSTRAINT "hhm_pre_interests_idea" CHECK (((char_length((entrepreneurship_idea)::text) >= 40) AND (char_length((entrepreneurship_idea)::text) <= 4000))),
  CONSTRAINT "hhm_pre_interests_idempotency_key_key" UNIQUE (idempotency_key),
  CONSTRAINT "hhm_pre_interests_linkedin" CHECK (((linkedin_url)::text ~ '^https://(www\.)?linkedin\.(com|cn)/in/'::text)),
  CONSTRAINT "hhm_pre_interests_mirror" CHECK ((((mirror_status)::text = 'pending'::text) OR ((mirror_status)::text = 'mirrored'::text) OR ((mirror_status)::text = 'retryable_failure'::text) OR ((mirror_status)::text = 'terminal_failure'::text))),
  CONSTRAINT "hhm_pre_interests_pkey" PRIMARY KEY (id),
  CONSTRAINT "hhm_pre_interests_sha256" CHECK ((payload_sha256 ~ '^[a-f0-9]{64}$'::text)),
  CONSTRAINT "hhm_pre_interests_stay" CHECK ((((stay_preference)::text = 'three_months'::text) OR ((stay_preference)::text = 'six_months'::text)))
);
CREATE INDEX hhm_pre_interests_created_idx ON public.hhm_pre_interests USING btree (created_at DESC);
CREATE INDEX hhm_pre_interests_email_idx ON public.hhm_pre_interests USING btree (lower((email)::text));
CREATE INDEX hhm_pre_interests_subject_idx ON public.hhm_pre_interests USING btree (applicant_subject) WHERE (applicant_subject IS NOT NULL);

-- create table: public.hhm_referrals
CREATE TABLE IF NOT EXISTS "public"."hhm_referrals" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "idempotency_key" character varying(128) NOT NULL,
  "payload_sha256" character(64) NOT NULL,
  "referrer_subject" character varying(255) NOT NULL,
  "referee_name" character varying(200) NOT NULL,
  "referee_email" character varying(320) NOT NULL,
  "referee_linkedin_url" character varying(500) NOT NULL,
  "relationship" character varying(120) NOT NULL,
  "rationale" character varying(4000) NOT NULL,
  "stay_preference" character varying(32),
  "nominee_consent_confirmed" boolean NOT NULL,
  "status" character varying(32) NOT NULL DEFAULT 'submitted'::character varying,
  "mirror_status" character varying(32) NOT NULL DEFAULT 'pending'::character varying,
  "created_at" timestamp with time zone NOT NULL DEFAULT transaction_timestamp(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT transaction_timestamp(),
  CONSTRAINT "hhm_referrals_consent" CHECK (nominee_consent_confirmed),
  CONSTRAINT "hhm_referrals_email" CHECK ((((referee_email)::text = btrim((referee_email)::text)) AND (POSITION(('@'::text) IN (referee_email)) > 1))),
  CONSTRAINT "hhm_referrals_idempotency_key_key" UNIQUE (idempotency_key),
  CONSTRAINT "hhm_referrals_linkedin" CHECK (((referee_linkedin_url)::text ~ '^https://(www\.)?linkedin\.(com|cn)/in/'::text)),
  CONSTRAINT "hhm_referrals_mirror" CHECK ((((mirror_status)::text = 'pending'::text) OR ((mirror_status)::text = 'mirrored'::text) OR ((mirror_status)::text = 'retryable_failure'::text) OR ((mirror_status)::text = 'terminal_failure'::text))),
  CONSTRAINT "hhm_referrals_pkey" PRIMARY KEY (id),
  CONSTRAINT "hhm_referrals_rationale" CHECK (((char_length((rationale)::text) >= 40) AND (char_length((rationale)::text) <= 4000))),
  CONSTRAINT "hhm_referrals_sha256" CHECK ((payload_sha256 ~ '^[a-f0-9]{64}$'::text)),
  CONSTRAINT "hhm_referrals_status" CHECK ((((status)::text = 'submitted'::text) OR ((status)::text = 'invited'::text) OR ((status)::text = 'applied'::text) OR ((status)::text = 'accepted'::text) OR ((status)::text = 'declined'::text))),
  CONSTRAINT "hhm_referrals_stay" CHECK (((stay_preference IS NULL) OR ((stay_preference)::text = 'three_months'::text) OR ((stay_preference)::text = 'six_months'::text)))
);
CREATE INDEX hhm_referrals_email_idx ON public.hhm_referrals USING btree (lower((referee_email)::text));
CREATE INDEX hhm_referrals_referrer_idx ON public.hhm_referrals USING btree (referrer_subject, created_at DESC);

-- create table: public.hhm_submission_outbox
CREATE TABLE IF NOT EXISTS "public"."hhm_submission_outbox" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "submission_kind" character varying(32) NOT NULL,
  "submission_id" uuid NOT NULL,
  "payload_sha256" character(64) NOT NULL,
  "mirror_status" character varying(32) NOT NULL DEFAULT 'pending'::character varying,
  "attempts" integer NOT NULL DEFAULT 0,
  "next_attempt_at" timestamp with time zone NOT NULL DEFAULT transaction_timestamp(),
  "last_error_code" character varying(64),
  "created_at" timestamp with time zone NOT NULL DEFAULT transaction_timestamp(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT transaction_timestamp(),
  CONSTRAINT "hhm_submission_outbox_attempts" CHECK (((attempts >= 0) AND (attempts <= 100))),
  CONSTRAINT "hhm_submission_outbox_identity" UNIQUE (submission_kind, submission_id),
  CONSTRAINT "hhm_submission_outbox_kind" CHECK ((((submission_kind)::text = 'pre_interest'::text) OR ((submission_kind)::text = 'upload'::text) OR ((submission_kind)::text = 'application'::text) OR ((submission_kind)::text = 'referral'::text))),
  CONSTRAINT "hhm_submission_outbox_mirror" CHECK ((((mirror_status)::text = 'pending'::text) OR ((mirror_status)::text = 'mirrored'::text) OR ((mirror_status)::text = 'retryable_failure'::text) OR ((mirror_status)::text = 'terminal_failure'::text))),
  CONSTRAINT "hhm_submission_outbox_pkey" PRIMARY KEY (id),
  CONSTRAINT "hhm_submission_outbox_sha256" CHECK ((payload_sha256 ~ '^[a-f0-9]{64}$'::text))
);
CREATE INDEX hhm_submission_outbox_retry_idx ON public.hhm_submission_outbox USING btree (next_attempt_at, created_at) WHERE (((mirror_status)::text = 'pending'::text) OR ((mirror_status)::text = 'retryable_failure'::text));

-- create table: public.hhm_user_points_accounts
CREATE TABLE IF NOT EXISTS "public"."hhm_user_points_accounts" (
  "subject" character varying(255) NOT NULL,
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "balance" bigint NOT NULL DEFAULT 0,
  "lifetime_earned" bigint NOT NULL DEFAULT 0,
  "lifetime_redeemed" bigint NOT NULL DEFAULT 0,
  "version" bigint NOT NULL DEFAULT 0,
  "updated_at" timestamp with time zone NOT NULL DEFAULT transaction_timestamp(),
  CONSTRAINT "hhm_user_points_accounts_balance" CHECK ((balance >= 0)),
  CONSTRAINT "hhm_user_points_accounts_id_key" UNIQUE (id),
  CONSTRAINT "hhm_user_points_accounts_pkey" PRIMARY KEY (subject),
  CONSTRAINT "hhm_user_points_accounts_totals" CHECK (((lifetime_earned >= 0) AND (lifetime_redeemed >= 0))),
  CONSTRAINT "hhm_user_points_accounts_version" CHECK ((version >= 0))
);

-- create table: public.hhm_user_points_ledger
CREATE TABLE IF NOT EXISTS "public"."hhm_user_points_ledger" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "idempotency_key" character varying(128) NOT NULL,
  "subject" character varying(255) NOT NULL,
  "delta" bigint NOT NULL,
  "reason_code" character varying(64) NOT NULL,
  "source_submission_id" uuid,
  "actor_subject" character varying(255) NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT transaction_timestamp(),
  CONSTRAINT "hhm_user_points_ledger_delta" CHECK ((delta <> 0)),
  CONSTRAINT "hhm_user_points_ledger_idempotency_key_key" UNIQUE (idempotency_key),
  CONSTRAINT "hhm_user_points_ledger_pkey" PRIMARY KEY (id),
  CONSTRAINT "hhm_user_points_ledger_reason" CHECK (((reason_code)::text ~ '^[a-z][a-z0-9_]{1,63}$'::text))
);
CREATE INDEX hhm_user_points_ledger_source_idx ON public.hhm_user_points_ledger USING btree (source_submission_id) WHERE (source_submission_id IS NOT NULL);
CREATE INDEX hhm_user_points_ledger_subject_idx ON public.hhm_user_points_ledger USING btree (subject, created_at DESC);

-- add constraint: hhm_applications_photo_id_upload_id_fkey on public.hhm_applications
ALTER TABLE "public"."hhm_applications" ADD CONSTRAINT "hhm_applications_photo_id_upload_id_fkey" FOREIGN KEY (photo_id_upload_id) REFERENCES public.hhm_intake_uploads(id) ON DELETE RESTRICT;

-- add constraint: hhm_applications_pre_interest_id_fkey on public.hhm_applications
ALTER TABLE "public"."hhm_applications" ADD CONSTRAINT "hhm_applications_pre_interest_id_fkey" FOREIGN KEY (pre_interest_id) REFERENCES public.hhm_pre_interests(id) ON DELETE SET NULL;

-- add constraint: hhm_applications_resume_upload_id_fkey on public.hhm_applications
ALTER TABLE "public"."hhm_applications" ADD CONSTRAINT "hhm_applications_resume_upload_id_fkey" FOREIGN KEY (resume_upload_id) REFERENCES public.hhm_intake_uploads(id) ON DELETE RESTRICT;

-- create function: public.hhm_apply_points_ledger_entry()
CREATE OR REPLACE FUNCTION public.hhm_apply_points_ledger_entry()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  updated_rows integer;
BEGIN
  IF NEW.delta > 0 THEN
    INSERT INTO hhm_user_points_accounts (
      subject, balance, lifetime_earned, lifetime_redeemed, version
    ) VALUES (
      NEW.subject,
      NEW.delta,
      NEW.delta,
      0,
      1
    )
    ON CONFLICT (subject) DO UPDATE SET
      balance = hhm_user_points_accounts.balance + NEW.delta,
      lifetime_earned = hhm_user_points_accounts.lifetime_earned + NEW.delta,
      version = hhm_user_points_accounts.version + 1,
      updated_at = transaction_timestamp();
  ELSE
    UPDATE hhm_user_points_accounts
    SET
      balance = balance + NEW.delta,
      lifetime_redeemed = lifetime_redeemed - NEW.delta,
      version = version + 1,
      updated_at = transaction_timestamp()
    WHERE subject = NEW.subject
      AND balance + NEW.delta >= 0;
  END IF;

  GET DIAGNOSTICS updated_rows = ROW_COUNT;
  IF updated_rows <> 1 THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'user points balance cannot become negative';
  END IF;
  RETURN NEW;
END;
$function$;

-- create function: public.hhm_forbid_points_ledger_mutation()
CREATE OR REPLACE FUNCTION public.hhm_forbid_points_ledger_mutation()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
BEGIN
  RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'user points ledger entries are immutable';
END;
$function$;

-- create function: public.hhm_touch_updated_at()
CREATE OR REPLACE FUNCTION public.hhm_touch_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
BEGIN
  NEW.updated_at := transaction_timestamp();
  RETURN NEW;
END;
$function$;

-- create trigger: public.hhm_applications.hhm_applications_touch_updated_at
CREATE TRIGGER hhm_applications_touch_updated_at BEFORE UPDATE ON public.hhm_applications FOR EACH ROW EXECUTE FUNCTION public.hhm_touch_updated_at();

-- create trigger: public.hhm_intake_uploads.hhm_intake_uploads_touch_updated_at
CREATE TRIGGER hhm_intake_uploads_touch_updated_at BEFORE UPDATE ON public.hhm_intake_uploads FOR EACH ROW EXECUTE FUNCTION public.hhm_touch_updated_at();

-- create trigger: public.hhm_pre_interests.hhm_pre_interests_touch_updated_at
CREATE TRIGGER hhm_pre_interests_touch_updated_at BEFORE UPDATE ON public.hhm_pre_interests FOR EACH ROW EXECUTE FUNCTION public.hhm_touch_updated_at();

-- create trigger: public.hhm_referrals.hhm_referrals_touch_updated_at
CREATE TRIGGER hhm_referrals_touch_updated_at BEFORE UPDATE ON public.hhm_referrals FOR EACH ROW EXECUTE FUNCTION public.hhm_touch_updated_at();

-- create trigger: public.hhm_submission_outbox.hhm_submission_outbox_touch_updated_at
CREATE TRIGGER hhm_submission_outbox_touch_updated_at BEFORE UPDATE ON public.hhm_submission_outbox FOR EACH ROW EXECUTE FUNCTION public.hhm_touch_updated_at();

-- create trigger: public.hhm_user_points_ledger.hhm_user_points_ledger_apply
CREATE TRIGGER hhm_user_points_ledger_apply AFTER INSERT ON public.hhm_user_points_ledger FOR EACH ROW EXECUTE FUNCTION public.hhm_apply_points_ledger_entry();

-- create trigger: public.hhm_user_points_ledger.hhm_user_points_ledger_immutable
CREATE TRIGGER hhm_user_points_ledger_immutable BEFORE DELETE OR UPDATE ON public.hhm_user_points_ledger FOR EACH ROW EXECUTE FUNCTION public.hhm_forbid_points_ledger_mutation();

-- enable row level security: public.hhm_applications
ALTER TABLE "public"."hhm_applications" ENABLE ROW LEVEL SECURITY;

-- force row level security: public.hhm_applications
ALTER TABLE "public"."hhm_applications" FORCE ROW LEVEL SECURITY;

-- create policy: hhm_applications_service_access on public.hhm_applications
CREATE POLICY "hhm_applications_service_access" ON "public"."hhm_applications" AS PERMISSIVE FOR ALL TO public USING ((CURRENT_USER = ANY (ARRAY['postgres'::name, 'service_role'::name, 'hhm_app_service'::name]))) WITH CHECK ((CURRENT_USER = ANY (ARRAY['postgres'::name, 'service_role'::name, 'hhm_app_service'::name])));

-- enable row level security: public.hhm_intake_uploads
ALTER TABLE "public"."hhm_intake_uploads" ENABLE ROW LEVEL SECURITY;

-- force row level security: public.hhm_intake_uploads
ALTER TABLE "public"."hhm_intake_uploads" FORCE ROW LEVEL SECURITY;

-- create policy: hhm_intake_uploads_service_access on public.hhm_intake_uploads
CREATE POLICY "hhm_intake_uploads_service_access" ON "public"."hhm_intake_uploads" AS PERMISSIVE FOR ALL TO public USING ((CURRENT_USER = ANY (ARRAY['postgres'::name, 'service_role'::name, 'hhm_app_service'::name]))) WITH CHECK ((CURRENT_USER = ANY (ARRAY['postgres'::name, 'service_role'::name, 'hhm_app_service'::name])));

-- enable row level security: public.hhm_pre_interests
ALTER TABLE "public"."hhm_pre_interests" ENABLE ROW LEVEL SECURITY;

-- force row level security: public.hhm_pre_interests
ALTER TABLE "public"."hhm_pre_interests" FORCE ROW LEVEL SECURITY;

-- create policy: hhm_pre_interests_service_access on public.hhm_pre_interests
CREATE POLICY "hhm_pre_interests_service_access" ON "public"."hhm_pre_interests" AS PERMISSIVE FOR ALL TO public USING ((CURRENT_USER = ANY (ARRAY['postgres'::name, 'service_role'::name, 'hhm_app_service'::name]))) WITH CHECK ((CURRENT_USER = ANY (ARRAY['postgres'::name, 'service_role'::name, 'hhm_app_service'::name])));

-- enable row level security: public.hhm_referrals
ALTER TABLE "public"."hhm_referrals" ENABLE ROW LEVEL SECURITY;

-- force row level security: public.hhm_referrals
ALTER TABLE "public"."hhm_referrals" FORCE ROW LEVEL SECURITY;

-- create policy: hhm_referrals_service_access on public.hhm_referrals
CREATE POLICY "hhm_referrals_service_access" ON "public"."hhm_referrals" AS PERMISSIVE FOR ALL TO public USING ((CURRENT_USER = ANY (ARRAY['postgres'::name, 'service_role'::name, 'hhm_app_service'::name]))) WITH CHECK ((CURRENT_USER = ANY (ARRAY['postgres'::name, 'service_role'::name, 'hhm_app_service'::name])));

-- enable row level security: public.hhm_submission_outbox
ALTER TABLE "public"."hhm_submission_outbox" ENABLE ROW LEVEL SECURITY;

-- force row level security: public.hhm_submission_outbox
ALTER TABLE "public"."hhm_submission_outbox" FORCE ROW LEVEL SECURITY;

-- create policy: hhm_submission_outbox_service_access on public.hhm_submission_outbox
CREATE POLICY "hhm_submission_outbox_service_access" ON "public"."hhm_submission_outbox" AS PERMISSIVE FOR ALL TO public USING ((CURRENT_USER = ANY (ARRAY['postgres'::name, 'service_role'::name, 'hhm_app_service'::name]))) WITH CHECK ((CURRENT_USER = ANY (ARRAY['postgres'::name, 'service_role'::name, 'hhm_app_service'::name])));

-- enable row level security: public.hhm_user_points_accounts
ALTER TABLE "public"."hhm_user_points_accounts" ENABLE ROW LEVEL SECURITY;

-- force row level security: public.hhm_user_points_accounts
ALTER TABLE "public"."hhm_user_points_accounts" FORCE ROW LEVEL SECURITY;

-- create policy: hhm_user_points_accounts_service_access on public.hhm_user_points_accounts
CREATE POLICY "hhm_user_points_accounts_service_access" ON "public"."hhm_user_points_accounts" AS PERMISSIVE FOR ALL TO public USING ((CURRENT_USER = ANY (ARRAY['postgres'::name, 'service_role'::name, 'hhm_app_service'::name]))) WITH CHECK ((CURRENT_USER = ANY (ARRAY['postgres'::name, 'service_role'::name, 'hhm_app_service'::name])));

-- enable row level security: public.hhm_user_points_ledger
ALTER TABLE "public"."hhm_user_points_ledger" ENABLE ROW LEVEL SECURITY;

-- force row level security: public.hhm_user_points_ledger
ALTER TABLE "public"."hhm_user_points_ledger" FORCE ROW LEVEL SECURITY;

-- create policy: hhm_user_points_ledger_service_access on public.hhm_user_points_ledger
CREATE POLICY "hhm_user_points_ledger_service_access" ON "public"."hhm_user_points_ledger" AS PERMISSIVE FOR ALL TO public USING ((CURRENT_USER = ANY (ARRAY['postgres'::name, 'service_role'::name, 'hhm_app_service'::name]))) WITH CHECK ((CURRENT_USER = ANY (ARRAY['postgres'::name, 'service_role'::name, 'hhm_app_service'::name])));

COMMIT;

-- changes: 43 total, 0 destructive (0 gated), 0 manual-review

-- Supabase-specific provider overlay. The cross-database authority intentionally
-- does not grant browser roles or own Storage provider configuration.
BEGIN;

REVOKE ALL PRIVILEGES ON TABLE
  public.hhm_applications,
  public.hhm_intake_uploads,
  public.hhm_pre_interests,
  public.hhm_referrals,
  public.hhm_submission_outbox,
  public.hhm_user_points_accounts,
  public.hhm_user_points_ledger
FROM anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE
  public.hhm_applications,
  public.hhm_intake_uploads,
  public.hhm_pre_interests,
  public.hhm_referrals,
  public.hhm_submission_outbox,
  public.hhm_user_points_accounts,
  public.hhm_user_points_ledger
TO service_role;

REVOKE EXECUTE ON FUNCTION public.hhm_apply_points_ledger_entry()
FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.hhm_forbid_points_ledger_mutation()
FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.hhm_touch_updated_at()
FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.hhm_apply_points_ledger_entry() TO service_role;
GRANT EXECUTE ON FUNCTION public.hhm_forbid_points_ledger_mutation() TO service_role;
GRANT EXECUTE ON FUNCTION public.hhm_touch_updated_at() TO service_role;

DROP POLICY IF EXISTS hhm_applications_service_access
  ON public.hhm_applications;
CREATE POLICY hhm_applications_service_access
  ON public.hhm_applications FOR ALL TO service_role
  USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS hhm_intake_uploads_service_access
  ON public.hhm_intake_uploads;
CREATE POLICY hhm_intake_uploads_service_access
  ON public.hhm_intake_uploads FOR ALL TO service_role
  USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS hhm_pre_interests_service_access
  ON public.hhm_pre_interests;
CREATE POLICY hhm_pre_interests_service_access
  ON public.hhm_pre_interests FOR ALL TO service_role
  USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS hhm_referrals_service_access
  ON public.hhm_referrals;
CREATE POLICY hhm_referrals_service_access
  ON public.hhm_referrals FOR ALL TO service_role
  USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS hhm_submission_outbox_service_access
  ON public.hhm_submission_outbox;
CREATE POLICY hhm_submission_outbox_service_access
  ON public.hhm_submission_outbox FOR ALL TO service_role
  USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS hhm_user_points_accounts_service_access
  ON public.hhm_user_points_accounts;
CREATE POLICY hhm_user_points_accounts_service_access
  ON public.hhm_user_points_accounts FOR ALL TO service_role
  USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS hhm_user_points_ledger_service_access
  ON public.hhm_user_points_ledger;
CREATE POLICY hhm_user_points_ledger_service_access
  ON public.hhm_user_points_ledger FOR ALL TO service_role
  USING (true) WITH CHECK (true);

INSERT INTO storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
VALUES (
  'hhm-intake-private',
  'hhm-intake-private',
  false,
  10485760,
  ARRAY[
    'application/pdf',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'image/jpeg',
    'image/png',
    'image/heic'
  ]
)
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

-- No anon/authenticated storage.objects policy is created. The API uses the
-- service-role boundary to issue bounded signed uploads after Turnstile or
-- Shared Auth verification, and verifies the stored object before acceptance.
COMMIT;



